{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "hermes-engine",
    "version": "0.70.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.14-debug.aar",
          "url": "hermes-engine-0.70.14-debug.aar",
          "size": 114190922,
          "sha512": "9c001c6cd12cc14b15ffee343355f4144f09d9247745d78a30796d5f083f9f745ec90e5b912a58a2759431a918798631de470cffec9f727b7c039e54002a4030",
          "sha256": "cd6518a65f597cdf79d540daede30007c74ade136584d6c49b4926031246aa63",
          "sha1": "217ccb7210b2b6c3acc0a411ff66bdafa6bc353b",
          "md5": "b809902a27401046aba56cf02e72d61d"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.14-debug.aar",
          "url": "hermes-engine-0.70.14-debug.aar",
          "size": 114190922,
          "sha512": "9c001c6cd12cc14b15ffee343355f4144f09d9247745d78a30796d5f083f9f745ec90e5b912a58a2759431a918798631de470cffec9f727b7c039e54002a4030",
          "sha256": "cd6518a65f597cdf79d540daede30007c74ade136584d6c49b4926031246aa63",
          "sha1": "217ccb7210b2b6c3acc0a411ff66bdafa6bc353b",
          "md5": "b809902a27401046aba56cf02e72d61d"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.14-debug-sources.jar",
          "url": "hermes-engine-0.70.14-debug-sources.jar",
          "size": 62707,
          "sha512": "b6d659b87a103dd21026d8715420d047b70e76219d39121795598811cff2c7bb6cf3a860d8836fe6eeb753f785d7c2f7b961ea48c5cba27626a6e1cb5b07ee62",
          "sha256": "1fe6791aeefb0391d319d763c655a6f8232676141b886d0a467b8834a0b86497",
          "sha1": "75340c383a5d55a37d68181f12b1d8d939a3f065",
          "md5": "7b864274b543d21ee7d7c9c8e7f7b043"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.14-release.aar",
          "url": "hermes-engine-0.70.14-release.aar",
          "size": 99260585,
          "sha512": "78774ff56244a3df7376e262433d35629b192a1c66ae3144850d022bb87dd8fc788683cdc50e8f1bb392e7ed77ee8313913fa750a80acb47af180120cfdf98a1",
          "sha256": "61b3caa58649795f90053af838d8bf6bdb4dc6825b494416dcd2613e6d250c2f",
          "sha1": "b7324227f6cb1c0b5148c4c7755b121a423eea71",
          "md5": "7b29309c80dea2d1427adb7fe40c099b"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.14-release.aar",
          "url": "hermes-engine-0.70.14-release.aar",
          "size": 99260585,
          "sha512": "78774ff56244a3df7376e262433d35629b192a1c66ae3144850d022bb87dd8fc788683cdc50e8f1bb392e7ed77ee8313913fa750a80acb47af180120cfdf98a1",
          "sha256": "61b3caa58649795f90053af838d8bf6bdb4dc6825b494416dcd2613e6d250c2f",
          "sha1": "b7324227f6cb1c0b5148c4c7755b121a423eea71",
          "md5": "7b29309c80dea2d1427adb7fe40c099b"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.14-release-sources.jar",
          "url": "hermes-engine-0.70.14-release-sources.jar",
          "size": 62694,
          "sha512": "205a0fd395d6d02c27c4611ae1ceca7ccb4f3554f17f44d338f9ffef2e3521e933616e74ac1b17bb7d300891ede5ecf58e966a11becda27f6760f862f2316783",
          "sha256": "e622d9a7db5ba1a2161785ab8745dda58d1012aad04f7f9489fce207cf567f8a",
          "sha1": "34cf662170d553da87ddd8ef2213f13212955d1d",
          "md5": "c8db891c3be1b407d7079c02c303243b"
        }
      ]
    }
  ]
}
